### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-NewPageMacro#5]
I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by netjunki** [comment]
I would love to join the track-hacks organization. I'd actually completely
forgotten that I'd written this plugin... 2012... hmmm must have been using
this at my old job...

Anyway sign me up. :-)

Cheers,
Ben

**Comment by rjollos** [comment]
Thanks!  You should receive two invites to join teams associated with the trac-hacks organization. One team gives you the general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. The second will give you Admin access for a group that your repository will be associated with. After you transfer the repository I'll remove you from the first team, but you'll continue to be an Admin for your repository by virtue of being a member of the second team.

Do you think any of the other Trac projects are worth moving? I see you have a trac-Pygit2. Jun has published [TracPygit2Plugin](http://trac-hacks.org/wiki/TracPygit2Plugin) and it will probably be added to tracopt by the release of Trac 1.2 (~July 2015). He's working from trac-hacks.org to prepare the plugin for integration to Trac.

**Comment by netjunki** [comment]
My fork of trac-Pygit2 was just me trying to understand/workaround a
performance issue I was encountering.

I'm not sure how useful the RecentReleases Macro is. I don't use trac for
any software projects anymore (had the unfortunate luck of landing two
places in a row which use Atlassian... ick) so I'm not sure of the value it
has.

Cheers,
Ben

**Comment by rjollos** [comment]
Thanks for transferring to the org. There is now a team with admin access that has the same name as the repository. You are currently the only team member, but you can add others if you like (or I'll be happy to do that with your permission on request).
